### ISSUE TITLE
Image is required in projects.yaml

### ISSUE THREAD

**Issue by lennnyyy** [wkocjan/gatsby-theme-intro#14]
In the readme, image is not required, however it gives an error when the image parameter is empty or removed.

 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "image" on type "ProjectsYaml".

If you don't expect "image" to exist on the type "ProjectsYaml" it is most likely a typo.
However, if you expect "image" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "image" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "ProjectsYaml":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: node_modules/@wkocjan/gatsby-theme-intro/src/templates/index.js:47:5

**Comment by wkocjan** [comment]
Thanks @lennnyyy  - this should be fixed now in `1.0.12` version.

Please run `yarn upgrade` to upgrade.
