### ISSUE TITLE
is there anyway to include Gatsby Blog theme into this?

### ISSUE THREAD

**Issue by DWShuo** [wkocjan/gatsby-theme-intro#15]
I'm currently trying to add blog pages to better explain each project, was wondering if there is a way to get Gatsby blog theme to work along side Gatsby theme intro. I'm following this guide https://www.gatsbyjs.com/tutorial/using-multiple-themes-together/ .
This is the error im getting if i install both themes `There was a problem loading the local develop command. Gatsby may not be installed. Perhaps you need to run "npm install"`

**Comment by wkocjan** [comment]
Yes, it's possible.

I'd recommend setting `basePath` parameter of `gatsby-theme-intro` to e.g. `/profile` - it's supported by the plugin, as you can read [here](https://github.com/wkocjan/gatsby-theme-intro#configuration).

**Comment by DWShuo** [comment]
Fixed the issue i was having. Use yarn to install the packages, don't use npm install like in the tutorials. Here is the link to the gatsby issue https://github.com/gatsbyjs/gatsby/issues/6834.

**Comment by wkocjan** [comment]
Glad it's working now for you with `yarn`. Thanks for info!
