### ISSUE TITLE
Optional display text for projects section

### ISSUE THREAD

**Issue by PallasStreams** [wkocjan/gatsby-theme-intro#18]
Not everyone will want to put work related projects and open source projects together. It would be good if there was an optional display text option where the header will say whatever text you put in there instead of "Projects" for my site I want it to be able to specify "Open Source Projects"

**Comment by wkocjan** [comment]
Hey, thanks for your suggestion. This one you can implement easily with [component shadowing](https://github.com/wkocjan/gatsby-theme-intro#component-shadowing ), that's why I'm closing this issue.
