### ISSUE TITLE
How to add new pages

### ISSUE THREAD

**Issue by ishanvyas22** [wkocjan/gatsby-theme-intro#19]
First of thanks for creating such a great theme. I wanted a help in adding a new page into this, I couldn't find any documentation regarding this.

My use case is,
- Add new button at the top named "Posts"
- That "Posts" should redirect to `/posts` page which lists the posts.

Can you please guide me how to achieve above things?

Thanks.

**Comment by DWShuo** [comment]
Where do you suggest the button to be added? i tired to do this a while ago too, but any additional buttons just looks out of place. you can refit the contact me button to direct you to the posts page. 

They way i currently have it is there is a blog icon under connect, and each project linking to its own blog page.

**Comment by wkocjan** [comment]
> Can you please guide me how to achieve above things?

To modify / extend the theme I'd recommend using Gatsby shadowing technique. Here is documentation about it:
https://www.gatsbyjs.com/docs/how-shadowing-works/
