### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by renzit** [wkocjan/gatsby-theme-intro#20]
First i would like to thank you and / or the team for the good work with this theme.
Here is my version of it: https://renzomayer.dev/ i want to add  2 languages support.

And my issue is; what would you recommend for having the same site in 2 languages?

I think 2 or 3 possibilities with gatsby config,
would be great if somebody already did this and can let me know their approach.

**Comment by wkocjan** [comment]
Thanks @renzit !

For multiple languages I'd recommend starting with this tutorial from Gatsby documentation:
https://www.gatsbyjs.com/docs/localization-i18n/

There are some Gatsby plugins you can use - I can't recommend a particular one, but I think whatever you choose, it should do the work.
