### ISSUE TITLE
Edit to README

### ISSUE THREAD

**Issue by SageewanSubendran** [wkocjan/gatsby-theme-intro#22]
Hey, really appreciate you sharing this theme!

I noticed I wasn't able to receive e-mails using Formspree even though I did set my email correctly in profile.yaml, and verified my email.
I did some digging and came across this: 
https://help.formspree.io/hc/en-us/articles/360056076314-Phasing-out-legacy-forms-email-URLs-

I replaced the e-mail field in profile.yaml with my form's endpoint (ex: https://formspree.io/**f/abcdefgh**) provided by Formspree, and everything worked out. Thought I would let you know, so the README can be updated when you get a chance. 

Thanks again!

**Comment by wkocjan** [comment]
Thanks @SageewanSubendran !

Just published the `1.1.0` version of the theme with changes. I ended up removing the `email` property from profile and instead used a more clear `formspreeEndpoint` property in `gatsby-config.js`. I've updated the README.md to reflect these changes, also added a short Changelog section explaining how to upgrade.
