### ISSUE TITLE
Error with Gatsby v3.0? 

### ISSUE THREAD

**Issue by TamimiGitHub** [wkocjan/gatsby-theme-intro#23]
When building my site using Gatsby v3.0 and this theme I get the following error

```
Missing onError handler for invocation 'building-schema', error was 'Enum "ImageFormat" cannot
represent value: "auto"'. Stacktrace was 'GraphQLError: Enum "ImageFormat" cannot represent value:
"auto"
```

Could this perhaps be due to the new image rendering functionality in Gatsby 3.0?

**Comment by wkocjan** [comment]
Hi,

Yes, the theme isn't compatible with v3 yet. I don't have a working solution right now, but eventually, I plan to upgrade the theme for v3.

**Comment by wkocjan** [comment]
Just released the `v2` version of the theme that is now compatible with Gatsby 3.

**Comment by TamimiGitHub** [comment]
Thanks for the update ! Will test it out and submit PR or open an issue should there be any bugs or issues I find along the way. Thank you for the quick turn around time!
