### ISSUE TITLE
Company website and logo

### ISSUE THREAD

**Issue by jkroepke** [wkocjan/gatsby-theme-intro#3]
Hi,

thanks for share this great theme.

If would be nice to enrich the work life entries with company logo and job description.

The company name could be a link to the company site if defined.

**Comment by wkocjan** [comment]
Hey,

Nice ideas, thanks! I've just added the `url` field to Work history section.

If you use the package, please just run `yarn upgrade` and then you can use this field in `work-history.yaml` file.

If you forked the repo, here is the commit which implements the change:
https://github.com/wkocjan/gatsby-theme-intro/commit/fc9b3561c510da9ac8189bb49083e9d971462b52

Regarding logo - currently I don't have plans to add it, it would require more serious design changes.
