### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by MirzaFaizan** [wkocjan/gatsby-theme-intro#4]
Thank you for such a great gatsby template. Can you guide me how can I add a favicon for my website?

**Comment by wkocjan** [comment]
Hey, thanks - glad you like it!

Regarding favicon:

- The easiest way is to create `static/` folder and put there `favicon.ico` file.

- For more sophisticated solution please check [gatsby-plugin-manifest](https://www.gatsbyjs.org/tutorial/part-eight/#add-a-manifest-file) plugin.

**Comment by MirzaFaizan** [comment]
Thank you.
