### ISSUE TITLE
Followed the steps in README.md , But it doesn't works, seems to be incompatible with node v13

### ISSUE THREAD

**Issue by TitusRobyK** [wkocjan/gatsby-theme-intro#5]
![image](https://user-images.githubusercontent.com/32787952/84103265-2d193400-aa30-11ea-8cb9-02c9eb936342.png)

**Comment by wkocjan** [comment]
Can you upgrade node to >=13.7 version? It looks like some package isn't compatible only with version from 13.3.0 to 13.7 range.
