### ISSUE TITLE
Image scaling issue on Chrome on mobile devices

### ISSUE THREAD

**Issue by mihaimpop** [wkocjan/gatsby-theme-intro#6]
Project images are not scaled properly when using Chrome on smartphones.
Firefox does not seem to be affected.

[Reference image](https://imgur.com/a/CCsBgbV)

**Comment by wkocjan** [comment]
Thanks for reporting it.

The problem was with long urls - just [fixed it](https://github.com/wkocjan/gatsby-theme-intro/commit/c6d67a304b6d726b5afe8022697460c52d791440) and released `1.0.7` version. Please update to the new version using `yarn upgrade`.
