### ISSUE TITLE
Bump package version

### ISSUE THREAD

**Issue by mihaimpop** [wkocjan/gatsby-theme-intro#8]
In my previous [commit](https://github.com/wkocjan/gatsby-theme-intro/commit/0df4660cdd18e95a2e81566d52ef612e936121b5)
https://github.com/wkocjan/gatsby-theme-intro/commit/0df4660cdd18e95a2e81566d52ef612e936121b5 I forgot to bump the package version.

Please update the package version and publish @npm the new package version.

**Comment by wkocjan** [comment]
Just updated version to `1.0.8`
